"""modulo1_identidad_config_bitacora

Revision ID: 7240d839b810
Revises: 
Create Date: 2026-08-03 08:42:40.952006
"""
from alembic import op
import sqlalchemy as sa


revision = '7240d839b810'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('colores',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('nombre', sa.String(length=60), nullable=False),
    sa.Column('hex', sa.String(length=7), nullable=False),
    sa.Column('activo', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.BigInteger(), server_default='1', nullable=False),
    sa.CheckConstraint("hex ~ '^#[0-9A-Fa-f]{6}$'", name=op.f('ck_colores_ck_colores_hex')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_colores')),
    sa.UniqueConstraint('codigo', name=op.f('uq_colores_codigo'))
    )
    op.create_table('permisos',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('codigo', sa.String(length=80), nullable=False),
    sa.Column('modulo', sa.String(length=40), nullable=False),
    sa.Column('recurso', sa.String(length=40), nullable=False),
    sa.Column('accion', sa.String(length=40), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.BigInteger(), server_default='1', nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_permisos')),
    sa.UniqueConstraint('codigo', name=op.f('uq_permisos_codigo'))
    )
    op.create_table('plantas',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('pais', sa.String(length=60), nullable=True),
    sa.Column('zona_horaria', sa.String(length=50), server_default='America/Mexico_City', nullable=False),
    sa.Column('idioma', sa.String(length=8), server_default='es', nullable=False),
    sa.Column('licencia', sa.JSON(), nullable=True),
    sa.Column('activo', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.BigInteger(), server_default='1', nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_plantas')),
    sa.UniqueConstraint('codigo', name=op.f('uq_plantas_codigo'))
    )
    op.create_table('roles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('codigo', sa.String(length=30), nullable=False),
    sa.Column('nombre', sa.String(length=60), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('es_sistema', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.BigInteger(), server_default='1', nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles')),
    sa.UniqueConstraint('codigo', name=op.f('uq_roles_codigo'))
    )
    op.create_table('usuarios',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('usuario', sa.String(length=60), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('nombre', sa.String(length=80), nullable=False),
    sa.Column('apellidos', sa.String(length=120), nullable=False),
    sa.Column('pin_hash', sa.String(length=255), nullable=True),
    sa.Column('rfid_tag', sa.String(length=64), nullable=True),
    sa.Column('qr_secret', sa.String(length=36), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('intentos_fallidos', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('bloqueado_hasta', sa.DateTime(timezone=True), nullable=True),
    sa.Column('estado', sa.String(length=20), server_default='activo', nullable=False),
    sa.Column('idioma', sa.String(length=8), server_default='es', nullable=False),
    sa.Column('ultima_conexion', sa.DateTime(timezone=True), nullable=True),
    sa.Column('creado_por', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.BigInteger(), server_default='1', nullable=False),
    sa.CheckConstraint("estado IN ('activo','inactivo','suspendido')", name=op.f('ck_usuarios_ck_usuarios_estado')),
    sa.CheckConstraint('char_length(usuario) >= 4', name=op.f('ck_usuarios_ck_usuarios_usuario_min')),
    sa.CheckConstraint('pin_hash IS NOT NULL OR rfid_tag IS NOT NULL OR qr_secret IS NOT NULL OR password_hash IS NOT NULL', name=op.f('ck_usuarios_ck_usuarios_credencial')),
    sa.ForeignKeyConstraint(['creado_por'], ['usuarios.id'], name=op.f('fk_usuarios_creado_por_usuarios')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_usuarios')),
    sa.UniqueConstraint('email', name=op.f('uq_usuarios_email')),
    sa.UniqueConstraint('qr_secret', name=op.f('uq_usuarios_qr_secret')),
    sa.UniqueConstraint('rfid_tag', name=op.f('uq_usuarios_rfid_tag')),
    sa.UniqueConstraint('usuario', name=op.f('uq_usuarios_usuario'))
    )
    op.create_index('ix_usuarios_estado', 'usuarios', ['estado'], unique=False)
    op.create_table('areas',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('planta_id', sa.String(length=36), nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('nombre', sa.String(length=80), nullable=False),
    sa.Column('responsable_id', sa.String(length=36), nullable=True),
    sa.Column('activo', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.BigInteger(), server_default='1', nullable=False),
    sa.ForeignKeyConstraint(['planta_id'], ['plantas.id'], name=op.f('fk_areas_planta_id_plantas')),
    sa.ForeignKeyConstraint(['responsable_id'], ['usuarios.id'], name=op.f('fk_areas_responsable_id_usuarios')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_areas')),
    sa.UniqueConstraint('planta_id', 'codigo', name='uq_areas_planta_codigo')
    )
    op.create_table('configuraciones_sistema',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('planta_id', sa.String(length=36), nullable=True),
    sa.Column('clave', sa.String(length=80), nullable=False),
    sa.Column('valor', sa.JSON(), nullable=False),
    sa.Column('tipo_dato', sa.String(length=20), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.Column('vigente', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['planta_id'], ['plantas.id'], name=op.f('fk_configuraciones_sistema_planta_id_plantas')),
    sa.ForeignKeyConstraint(['updated_by'], ['usuarios.id'], name=op.f('fk_configuraciones_sistema_updated_by_usuarios')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_configuraciones_sistema')),
    sa.UniqueConstraint('clave', name='uq_config_global')
    )
    op.create_table('estados',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('planta_id', sa.String(length=36), nullable=True),
    sa.Column('proceso', sa.String(length=40), nullable=False),
    sa.Column('codigo', sa.String(length=30), nullable=False),
    sa.Column('nombre', sa.String(length=80), nullable=False),
    sa.Column('activo', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.BigInteger(), server_default='1', nullable=False),
    sa.ForeignKeyConstraint(['planta_id'], ['plantas.id'], name=op.f('fk_estados_planta_id_plantas')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_estados')),
    sa.UniqueConstraint('proceso', 'codigo', 'planta_id', name='uq_estados_proceso_codigo_planta')
    )
    op.create_table('rol_permisos',
    sa.Column('rol_id', sa.String(length=36), nullable=False),
    sa.Column('permiso_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['permiso_id'], ['permisos.id'], name=op.f('fk_rol_permisos_permiso_id_permisos'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rol_id'], ['roles.id'], name=op.f('fk_rol_permisos_rol_id_roles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('rol_id', 'permiso_id', name=op.f('pk_rol_permisos')),
    sa.UniqueConstraint('rol_id', 'permiso_id', name='uq_rol_permisos_rol_permiso')
    )
    op.create_table('sesiones_autenticacion',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('usuario_id', sa.String(length=36), nullable=False),
    sa.Column('refresh_hash', sa.String(length=64), nullable=False),
    sa.Column('jti', sa.String(length=36), nullable=False),
    sa.Column('expira', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revocada', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('dispositivo', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], name=op.f('fk_sesiones_autenticacion_usuario_id_usuarios'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sesiones_autenticacion')),
    sa.UniqueConstraint('refresh_hash', name=op.f('uq_sesiones_autenticacion_refresh_hash'))
    )
    op.create_index('ix_sesiones_autenticacion_jti', 'sesiones_autenticacion', ['jti'], unique=False)
    op.create_index('ix_sesiones_autenticacion_usuario_activa', 'sesiones_autenticacion', ['usuario_id'], unique=False)
    op.create_table('turnos',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('planta_id', sa.String(length=36), nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('nombre', sa.String(length=60), nullable=False),
    sa.Column('hora_inicio', sa.Time(), nullable=False),
    sa.Column('hora_fin', sa.Time(), nullable=False),
    sa.Column('activo', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.BigInteger(), server_default='1', nullable=False),
    sa.CheckConstraint('hora_fin <> hora_inicio', name=op.f('ck_turnos_ck_turnos_horas_distintas')),
    sa.ForeignKeyConstraint(['planta_id'], ['plantas.id'], name=op.f('fk_turnos_planta_id_plantas')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_turnos')),
    sa.UniqueConstraint('planta_id', 'codigo', name='uq_turnos_planta_codigo')
    )
    op.create_table('usuarios_roles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('usuario_id', sa.String(length=36), nullable=False),
    sa.Column('planta_id', sa.String(length=36), nullable=False),
    sa.Column('rol_id', sa.String(length=36), nullable=False),
    sa.Column('vigencia_inicio', sa.Date(), nullable=False),
    sa.Column('vigencia_fin', sa.Date(), nullable=True),
    sa.Column('activo', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.CheckConstraint('vigencia_fin IS NULL OR vigencia_fin >= vigencia_inicio', name=op.f('ck_usuarios_roles_ck_usuarios_roles_vigencia')),
    sa.ForeignKeyConstraint(['planta_id'], ['plantas.id'], name=op.f('fk_usuarios_roles_planta_id_plantas')),
    sa.ForeignKeyConstraint(['rol_id'], ['roles.id'], name=op.f('fk_usuarios_roles_rol_id_roles')),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], name=op.f('fk_usuarios_roles_usuario_id_usuarios')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_usuarios_roles')),
    sa.UniqueConstraint('usuario_id', 'planta_id', 'rol_id', name='uq_usuarios_roles_usuario_planta_rol')
    )
    op.create_index('ix_usuarios_roles_usuario_activo', 'usuarios_roles', ['usuario_id', 'activo'], unique=False)
    op.create_table('maquinas',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('planta_id', sa.String(length=36), nullable=False),
    sa.Column('area_id', sa.String(length=36), nullable=False),
    sa.Column('codigo', sa.String(length=30), nullable=False),
    sa.Column('nombre', sa.String(length=80), nullable=False),
    sa.Column('tiene_contador', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('tipo_contador', sa.String(length=10), server_default='ninguno', nullable=False),
    sa.Column('velocidad_maxima', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('config_contador', sa.JSON(), nullable=True),
    sa.Column('parametros', sa.JSON(), nullable=True),
    sa.Column('estado_actual_id', sa.String(length=36), nullable=False),
    sa.Column('activo', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.BigInteger(), server_default='1', nullable=False),
    sa.CheckConstraint("(tiene_contador = false AND tipo_contador = 'ninguno') OR (tiene_contador = true AND tipo_contador IN ('opc','manual'))", name=op.f('ck_maquinas_ck_maquinas_contador')),
    sa.ForeignKeyConstraint(['area_id'], ['areas.id'], name=op.f('fk_maquinas_area_id_areas')),
    sa.ForeignKeyConstraint(['estado_actual_id'], ['estados.id'], name=op.f('fk_maquinas_estado_actual_id_estados')),
    sa.ForeignKeyConstraint(['planta_id'], ['plantas.id'], name=op.f('fk_maquinas_planta_id_plantas')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_maquinas')),
    sa.UniqueConstraint('planta_id', 'codigo', name='uq_maquinas_planta_codigo')
    )
    op.create_table('turnos_dias',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('turno_id', sa.String(length=36), nullable=False),
    sa.Column('dia_semana', sa.Integer(), nullable=False),
    sa.CheckConstraint('dia_semana BETWEEN 1 AND 7', name=op.f('ck_turnos_dias_ck_turnos_dias_dia')),
    sa.ForeignKeyConstraint(['turno_id'], ['turnos.id'], name=op.f('fk_turnos_dias_turno_id_turnos'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_turnos_dias')),
    sa.UniqueConstraint('turno_id', 'dia_semana', name='uq_turnos_dias_turno_dia')
    )
    op.create_table('kioskos',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('planta_id', sa.String(length=36), nullable=False),
    sa.Column('maquina_id', sa.String(length=36), nullable=True),
    sa.Column('codigo', sa.String(length=30), nullable=False),
    sa.Column('tipo_ingreso', sa.String(length=10), nullable=False),
    sa.Column('token_dispositivo', sa.String(length=64), nullable=False),
    sa.Column('ubicacion', sa.String(length=120), nullable=True),
    sa.Column('activo', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.BigInteger(), server_default='1', nullable=False),
    sa.CheckConstraint("tipo_ingreso IN ('qr','rfid','pin','mixto')", name=op.f('ck_kioskos_ck_kioskos_tipo_ingreso')),
    sa.ForeignKeyConstraint(['maquina_id'], ['maquinas.id'], name=op.f('fk_kioskos_maquina_id_maquinas')),
    sa.ForeignKeyConstraint(['planta_id'], ['plantas.id'], name=op.f('fk_kioskos_planta_id_plantas')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_kioskos')),
    sa.UniqueConstraint('planta_id', 'codigo', name='uq_kioskos_planta_codigo'),
    sa.UniqueConstraint('token_dispositivo', name=op.f('uq_kioskos_token_dispositivo'))
    )
    # bitacora particionada por RANGE mensual (DB-04). SQLAlchemy no genera
    # particionado nativo: se crea con DDL directo (padre + particion default).
    op.execute("""
        CREATE TABLE bitacora (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY,
            planta_id VARCHAR(36),
            usuario_id VARCHAR(36),
            accion VARCHAR(60) NOT NULL,
            modulo VARCHAR(40) NOT NULL,
            entidad VARCHAR(60) NOT NULL,
            entidad_id VARCHAR(64),
            valor_anterior JSONB,
            valor_nuevo JSONB,
            ip VARCHAR(45),
            dispositivo VARCHAR(255),
            kiosko_id VARCHAR(36),
            fecha TIMESTAMPTZ NOT NULL DEFAULT now(),
            CONSTRAINT pk_bitacora PRIMARY KEY (id, fecha),
            CONSTRAINT fk_bitacora_planta_id_plantas FOREIGN KEY (planta_id) REFERENCES plantas (id),
            CONSTRAINT fk_bitacora_usuario_id_usuarios FOREIGN KEY (usuario_id) REFERENCES usuarios (id),
            CONSTRAINT fk_bitacora_kiosko_id_kioskos FOREIGN KEY (kiosko_id) REFERENCES kioskos (id)
        ) PARTITION BY RANGE (fecha)
    """)
    op.execute("CREATE TABLE bitacora_default PARTITION OF bitacora DEFAULT")
    op.create_index('ix_bitacora_accion', 'bitacora', ['accion', 'fecha'], unique=False)
    op.create_index('ix_bitacora_entidad', 'bitacora', ['entidad', 'entidad_id'], unique=False)
    op.create_index('ix_bitacora_usuario', 'bitacora', ['usuario_id', 'fecha'], unique=False)
    op.create_table('sesiones_operario',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('planta_id', sa.String(length=36), nullable=False),
    sa.Column('usuario_id', sa.String(length=36), nullable=False),
    sa.Column('maquina_id', sa.String(length=36), nullable=False),
    sa.Column('turno_id', sa.String(length=36), nullable=True),
    sa.Column('kiosko_id', sa.String(length=36), nullable=False),
    sa.Column('metodo_acceso', sa.String(length=10), nullable=False),
    sa.Column('hora_inicio', sa.DateTime(timezone=True), nullable=False),
    sa.Column('hora_fin', sa.DateTime(timezone=True), nullable=True),
    sa.Column('motivo_cierre', sa.String(length=20), nullable=True),
    sa.Column('estado', sa.String(length=20), server_default='activa', nullable=False),
    sa.CheckConstraint("metodo_acceso IN ('qr','rfid','pin')", name=op.f('ck_sesiones_operario_ck_sesiones_operario_metodo')),
    sa.CheckConstraint("motivo_cierre IS NULL OR motivo_cierre IN ('logout','timeout','cambio_maquina','fin_turno','reemplazo')", name=op.f('ck_sesiones_operario_ck_sesiones_operario_motivo')),
    sa.CheckConstraint('hora_fin IS NULL OR hora_fin > hora_inicio', name=op.f('ck_sesiones_operario_ck_sesiones_operario_horas')),
    sa.ForeignKeyConstraint(['kiosko_id'], ['kioskos.id'], name=op.f('fk_sesiones_operario_kiosko_id_kioskos')),
    sa.ForeignKeyConstraint(['maquina_id'], ['maquinas.id'], name=op.f('fk_sesiones_operario_maquina_id_maquinas')),
    sa.ForeignKeyConstraint(['planta_id'], ['plantas.id'], name=op.f('fk_sesiones_operario_planta_id_plantas')),
    sa.ForeignKeyConstraint(['turno_id'], ['turnos.id'], name=op.f('fk_sesiones_operario_turno_id_turnos')),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], name=op.f('fk_sesiones_operario_usuario_id_usuarios'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sesiones_operario'))
    )
    op.create_index('ix_sesiones_operario_maquina_activa', 'sesiones_operario', ['maquina_id'], unique=False)
    op.create_index('ix_sesiones_operario_turno', 'sesiones_operario', ['turno_id', 'hora_inicio'], unique=False)
    op.create_index('ix_sesiones_operario_usuario_activa', 'sesiones_operario', ['usuario_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_sesiones_operario_usuario_activa', table_name='sesiones_operario')
    op.drop_index('ix_sesiones_operario_turno', table_name='sesiones_operario')
    op.drop_index('ix_sesiones_operario_maquina_activa', table_name='sesiones_operario')
    op.drop_table('sesiones_operario')
    op.drop_index('ix_bitacora_usuario', table_name='bitacora')
    op.drop_index('ix_bitacora_entidad', table_name='bitacora')
    op.drop_index('ix_bitacora_accion', table_name='bitacora')
    op.execute("DROP TABLE bitacora")
    op.drop_table('kioskos')
    op.drop_table('turnos_dias')
    op.drop_table('maquinas')
    op.drop_index('ix_usuarios_roles_usuario_activo', table_name='usuarios_roles')
    op.drop_table('usuarios_roles')
    op.drop_table('turnos')
    op.drop_index('ix_sesiones_autenticacion_usuario_activa', table_name='sesiones_autenticacion')
    op.drop_index('ix_sesiones_autenticacion_jti', table_name='sesiones_autenticacion')
    op.drop_table('sesiones_autenticacion')
    op.drop_table('rol_permisos')
    op.drop_table('estados')
    op.drop_table('configuraciones_sistema')
    op.drop_table('areas')
    op.drop_index('ix_usuarios_estado', table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_table('roles')
    op.drop_table('plantas')
    op.drop_table('permisos')
    op.drop_table('colores')
    # ### end Alembic commands ###
